// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-j-AiYNEsqq4mY0gZvJDYX3egkU1wEI',
    appId: '1:734235580820:web:fc98567dd57e32083cd781',
    messagingSenderId: '734235580820',
    projectId: 'chat-app-38aca',
    authDomain: 'chat-app-38aca.firebaseapp.com',
    storageBucket: 'chat-app-38aca.firebasestorage.app',
    measurementId: 'G-LZEC1BKW47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijNHw16YCwcPsNjwadGuYXDPYK51xhDI',
    appId: '1:734235580820:android:dcfeee9432598aae3cd781',
    messagingSenderId: '734235580820',
    projectId: 'chat-app-38aca',
    storageBucket: 'chat-app-38aca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKTr-qKi-NT6LzW7fQwi_hKwWsBd14oo',
    appId: '1:734235580820:ios:0540e7223e5c0d2a3cd781',
    messagingSenderId: '734235580820',
    projectId: 'chat-app-38aca',
    storageBucket: 'chat-app-38aca.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKTr-qKi-NT6LzW7fQwi_hKwWsBd14oo',
    appId: '1:734235580820:ios:0540e7223e5c0d2a3cd781',
    messagingSenderId: '734235580820',
    projectId: 'chat-app-38aca',
    storageBucket: 'chat-app-38aca.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa-j-AiYNEsqq4mY0gZvJDYX3egkU1wEI',
    appId: '1:734235580820:web:f1314191175c4bba3cd781',
    messagingSenderId: '734235580820',
    projectId: 'chat-app-38aca',
    authDomain: 'chat-app-38aca.firebaseapp.com',
    storageBucket: 'chat-app-38aca.firebasestorage.app',
    measurementId: 'G-9WSWGG2033',
  );
}
